# Generated by Django 5.1.2 on 2024-10-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_avatar.png', upload_to='profile_pics/'),
        ),
    ]
