# Generated by Django 5.1.2 on 2024-10-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_project', '0003_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_avatar.png', upload_to='profile_pics/'),
        ),
    ]
