# Generated by Django 5.1.2 on 2024-10-16 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_project', '0006_expense_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sk_project.mainbudget'),
        ),
    ]
