# Generated by Django 5.1.2 on 2024-10-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_project', '0007_alter_project_main_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allocated_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
