# Generated by Django 5.1.2 on 2024-10-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_project', '0008_project_allocated_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbudget',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='mainbudget',
            unique_together={('year', 'chairman')},
        ),
    ]
