# Generated by Django 4.2.7 on 2025-01-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sk_project', '0010_accomplishmentreport_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishmentreport',
            name='images',
        ),
        migrations.CreateModel(
            name='AccomplishmentReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accomplishment_reports/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_images', to='sk_project.accomplishmentreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
