# Generated by Django 4.2.7 on 2025-01-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_project', '0012_project_image_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_final_images/%Y/%m/%d/'),
        ),
    ]
